name: 'R CMD check'
description: 'Prepare and check a package'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true
  checkargs:
    description: 'Extra args for R CMD check'
    default: --no-manual --no-build-vignettes
    required: true
  cranlikerepo:
    description: 'URL of the package repository with dependencies'
    default: 'Sys.getenv("MY_UNIVERSE", "https://dev.ropensci.org")'
    required: true

runs:
  using: "composite"
  steps: 
    - name: "Setup R package library"
      shell: bash
      run: |
        if [ "${R_LIBS_USER}" ]; then mkdir -p $R_LIBS_USER; fi
        echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > $R_PROFILE_USER
        echo 'options(Ncpus = 2, crayon.enabled = TRUE)' >> $R_PROFILE_USER
        echo 'utils::setRepositories(ind = 1:2)' >> $R_PROFILE_USER
        echo 'options(repos = c(universe = ${{inputs.cranlikerepo}}, getOption("repos")))' >> $R_PROFILE_USER
        cat $R_PROFILE_USER
      env:
        R_PROFILE_USER: .Rprofile
    - name: Install package dependencies
      run: |
        install.packages('remotes')
        pkg_deps <- remotes::local_package_deps("${{inputs.sourcepkg}}", dependencies = TRUE)
        installed <- row.names(installed.packages())
        pkg_deps <- pkg_deps[is.na(match(pkg_deps, installed))]
        install.packages(pkg_deps)
      shell: Rscript {0}
      env:
        R_COMPILE_AND_INSTALL_PACKAGES: never
    - name: Build and check package
      shell: bash
      run: R CMD check ${{inputs.sourcepkg}} --install-args="--build" ${{inputs.checkargs}}
      env:
        R_BROWSER: echo
        R_PDFVIEWER: echo
        RGL_USE_NULL: TRUE
        R_TEXI2DVICMD: emulation
        NOT_CRAN: FALSE
        PKG_CONFIG_PATH: /opt/X11/lib/pkgconfig
        R_PROFILE_USER: .Rprofile
        _R_CHECK_FORCE_SUGGESTS_: FALSE
        _R_CHECK_CRAN_INCOMING_: FALSE
        _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
