name: 'R CMD check'
description: 'Prepare and check a package'
inputs:
  sourcepkg:
    description: 'File of the source package'
    required: true
  checkargs:
    description: 'Extra args for R CMD check'
    default: --no-manual --no-build-vignettes
    required: true
  cranlikerepo:
    description: 'URL of the package repository with dependencies'
    default: 'Sys.getenv("MY_UNIVERSE", "https://dev.ropensci.org")'
    required: true
  java:
    description: 'Package depends on rJava'
    required: false

runs:
  using: "composite"
  steps:
    - name: "Update pacman"
      run: |
        pacman -Sy --noconfirm --needed mingw-w64-{i686,x86_64}-{gsl,fftw} || true
      shell: c:\rtools40\usr\bin\bash.exe --login {0}

    - name: "Install Java if needed"
      run: choco install jre8 -PackageParameters "/exclude:64" -y
      if: ${{inputs.java}}

    - name: "Setup R package library"
      shell: bash
      run: |
        echo "::group::Setup R package library"
        if [ "${R_LIBS_USER}" ]; then mkdir -p $R_LIBS_USER; fi
        echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > $R_PROFILE_USER
        echo 'options(Ncpus = 2, crayon.enabled = TRUE)' >> $R_PROFILE_USER
        echo 'if(grepl("4.0", getRversion())) Sys.setenv(R_BIOC_VERSION=3.12)' >> $R_PROFILE_USER
        echo 'utils::setRepositories(ind = 1:3)' >> $R_PROFILE_USER
        echo 'Sys.unsetenv(c("CI", "GITHUB_ACTIONS"))' >> $R_PROFILE_USER
        echo 'options(repos = c(universe = trimws(strsplit(${{inputs.cranlikerepo}}, ";")[[1]]), getOption("repos")))' >> $R_PROFILE_USER
        cat $R_PROFILE_USER
        echo "::endgroup::"
      env:
        R_PROFILE_USER: .Rprofile
    - name: Install package dependencies
      run: |
        cat('::group::Install package dependencies\n')
        install.packages('remotes')
        pkg_deps <- remotes::local_package_deps("${{inputs.sourcepkg}}", dependencies = TRUE)
        installed <- row.names(installed.packages())
        needpkg <- setdiff(pkg_deps, installed)
        avail <- row.names(available.packages())
        install <- intersect(needpkg, avail)
        unavail <- setdiff(needpkg, avail)
        install.packages(install)
        if(length(unavail)) {
          warning("Installing from remotes: ", paste(unavail, collapse = ','))
          remotes::install_deps("${{inputs.sourcepkg}}", dependencies = TRUE, upgrade = FALSE)
        }
        cat('::endgroup::\n')
      shell: Rscript {0}
      env:
        R_COMPILE_AND_INSTALL_PACKAGES: never
    - name: Build and check package
      shell: cmd
      run: R CMD check ${{inputs.sourcepkg}} --install-args="--build" ${{inputs.checkargs}}
      env:
        R_BROWSER: echo
        R_PDFVIEWER: echo
        RGL_USE_NULL: TRUE
        R_TEXI2DVICMD: emulation
        NOT_CRAN: FALSE
        PKG_CONFIG_PATH: /opt/X11/lib/pkgconfig
        R_PROFILE_USER: .Rprofile
        _R_CHECK_FORCE_SUGGESTS_: FALSE
        _R_CHECK_CRAN_INCOMING_: FALSE
        _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
